# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('population', models.IntegerField()),
                ('growth', models.TextField()),
            ],
        ),
    ]
