# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klaviyo_weather_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('timezone', models.TextField()),
                ('creationTime', models.DateTimeField()),
                ('cityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klaviyo_weather_api.City')),
            ],
        ),
    ]
