# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 06:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klaviyo_weather_api', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city',
            new_name='name',
        ),
    ]
